import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div className="flex flex-col min-h-screen">
  <div className="px-6 py-6">
    <Navigation />
  </div>
  <main className="flex-1 max-w-auto mx-auto p-6 bg-gradient-to-r from-yellow-500 to-teal-500 md:w-full">
    {children}
  </main>
</div>

      </body>
    </html>
  );
}
